### ISSUE TITLE
Send mail over socks example?

### ISSUE THREAD

**Issue by remotehelp** [clue/php-socks#9]
Hello!

It would be nice if you present send mail over socks example.

Thank.

**Comment by clue** [comment]
This repository is currently in maintenance mode, may I ask you to file this over at https://github.com/clue/php-socks-react instead? :+1: 

Also, please provide some more details, such as which mailer you're using and if it supports connections through SOCKS proxies at all.

**Comment by xzhonour** [comment]
I also need to send email through proxy, but I don't know where to start. At present, it is possible to request HTTP only through proxy. I urgently need to send email through proxy! Can you help me?
